steps:
# Pull most recent Docker image.
- id: 'pull-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '${_DOCKER_IMAGE}']
  waitFor: ['-']

# Run presubmit tests.
- id: 'build-and-test'
  waitFor: ['pull-image']
  name: '${_DOCKER_IMAGE}'
  entrypoint: 'bash'
  args: ['./kokoro/build.sh']
  env:
    - 'REPO_NAME=${REPO_NAME}'
    - 'COMMIT_SHA=${COMMIT_SHA}'

timeout: 3600s # 60 mins, just in case.

substitutions:
  _DOCKER_IMAGE: us-central1-docker.pkg.dev/private-compute-libraries-ci/docker-images/pcl-image:latest

options:
  machineType: 'E2_HIGHCPU_32'

