load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "AnnotationProtoTest",
    srcs = ["AnnotationProtoTest.kt"],
    deps = [
        "//java/com/google/android/libraries/pcc/chronicle/api/policy",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/annotation",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/contextrules",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/proto",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/proto:annotation_java_proto_lite",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/proto:policy_java_proto_lite",
        "//java/com/google/android/libraries/pcc/chronicle/util:typed_map",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
    ],
)

kt_jvm_test(
    name = "PolicyProtoTest",
    srcs = ["PolicyProtoTest.kt"],
    deps = [
        "//java/com/google/android/libraries/pcc/chronicle/api/policy",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/annotation",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/contextrules",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/proto",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/proto:annotation_java_proto_lite",
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/proto:policy_java_proto_lite",
        "//java/com/google/android/libraries/pcc/chronicle/util:typed_map",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
    ],
)
