load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_library")

package(default_visibility = [
    "//visibility:public",
])

kt_jvm_library(
    name = "contextrules",
    srcs = [
        "PolicyContextRule.kt",
    ],
    deps = ["//java/com/google/android/libraries/pcc/chronicle/util:typed_map"],
)
