load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_library")

package(default_visibility = [
    "//visibility:public",
])

kt_jvm_library(
    name = "annotation",
    srcs = glob(["*.kt"]),
    deps = [],
)
