load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "PolicyContextRuleTest",
    srcs = ["PolicyContextRuleTest.kt"],
    deps = [
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/contextrules",
        "//java/com/google/android/libraries/pcc/chronicle/util:typed_map",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
