load("@bazel_rules_android//android:rules.bzl", "android_library")
load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

android_library(
    name = "operation",
    srcs = glob(["*.kt"]),
)

kt_jvm_library(
    name = "operation_jvm",
    srcs = glob(["*.kt"]),
)
