load("//tools/build_defs/kotlin:rules.bzl", "kt_android_library", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_android_library(
    name = "operation",
    srcs = glob(["*.kt"]),
)

kt_jvm_library(
    name = "operation_jvm",
    srcs = glob(["*.kt"]),
)
