load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "AnnotationBuilderTest",
    srcs = ["AnnotationBuilderTest.kt"],
    deps = [
        "//java/com/google/android/libraries/pcc/chronicle/api/policy/annotation",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
    ],
)
